"""Export commands - generate Terraform/Ansible from existing resources."""

from pathlib import Path

import typer
from rich.console import Console

from dom.utils import get_client

app = typer.Typer(no_args_is_help=True)
console = Console()


# Default paths
TERRAFORM_DIR = Path("./terraform/generated")
ANSIBLE_DIR = Path("./ansible/inventory")


@app.command("terraform")
def export_terraform(
    output: Path = typer.Option(None, "--output", "-o", help="Output directory (default: ./terraform/generated)"),
    resource_type: str = typer.Option("all", "--type", "-t", help="Resource type: all, droplets, volumes, domains"),
):
    if output is None:
        output = TERRAFORM_DIR
    """Generate Terraform configurations from existing resources."""
    client = get_client()

    output.mkdir(parents=True, exist_ok=True)

    console.print(f"\n[bold]Exporting to Terraform[/bold] -> {output}\n")

    tf_content = '''# Generated by dom export terraform
# Review and modify before using!

terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }
}

variable "do_token" {
  description = "DigitalOcean API Token"
  type        = string
  sensitive   = true
}

provider "digitalocean" {
  token = var.do_token
}

'''

    import_commands = []

    # Export Droplets
    if resource_type in ["all", "droplets"]:
        droplets = client.droplets.list().get("droplets", [])

        for d in droplets:
            name = d["name"].replace("-", "_").replace(".", "_")
            tf_content += f'''
# Droplet: {d["name"]}
resource "digitalocean_droplet" "{name}" {{
  name     = "{d["name"]}"
  size     = "{d["size_slug"]}"
  image    = "{d["image"]["slug"]}"
  region   = "{d["region"]["slug"]}"
  vpc_uuid = "{d.get("vpc_uuid", "")}"
  tags     = {d.get("tags", [])}
}}
'''
            import_commands.append(f"terraform import digitalocean_droplet.{name} {d['id']}")

        console.print(f"  [green]Droplets:[/green] {len(droplets)}")

    # Export Volumes
    if resource_type in ["all", "volumes"]:
        volumes = client.volumes.list().get("volumes", [])

        for v in volumes:
            name = v["name"].replace("-", "_").replace(".", "_")
            tf_content += f'''
# Volume: {v["name"]}
resource "digitalocean_volume" "{name}" {{
  name                    = "{v["name"]}"
  region                  = "{v["region"]["slug"]}"
  size                    = {v["size_gigabytes"]}
  initial_filesystem_type = "{v.get("filesystem_type", "ext4")}"
  description             = "{v.get("description", "")}"
}}
'''
            import_commands.append(f"terraform import digitalocean_volume.{name} {v['id']}")

        console.print(f"  [green]Volumes:[/green] {len(volumes)}")

    # Export Domains
    if resource_type in ["all", "domains"]:
        domains = client.domains.list().get("domains", [])

        for domain in domains:
            name = domain["name"].replace("-", "_").replace(".", "_")
            tf_content += f'''
# Domain: {domain["name"]}
resource "digitalocean_domain" "{name}" {{
  name = "{domain["name"]}"
}}
'''
            import_commands.append(f"terraform import digitalocean_domain.{name} {domain['name']}")

        console.print(f"  [green]Domains:[/green] {len(domains)}")

    # Export Firewalls
    if resource_type in ["all", "firewalls"]:
        try:
            firewalls = client.firewalls.list().get("firewalls", [])

            for fw in firewalls:
                name = fw["name"].replace("-", "_").replace(".", "_")
                tf_content += f'''
# Firewall: {fw["name"]}
resource "digitalocean_firewall" "{name}" {{
  name = "{fw["name"]}"
  # TODO: Add inbound_rule and outbound_rule blocks
  # See: https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/firewall
}}
'''
                import_commands.append(f"terraform import digitalocean_firewall.{name} {fw['id']}")

            console.print(f"  [green]Firewalls:[/green] {len(firewalls)}")
        except Exception:
            pass

    # Write main.tf
    main_tf = output / "main.tf"
    main_tf.write_text(tf_content)
    console.print(f"\n  Written: {main_tf}")

    # Write import script
    if import_commands:
        import_sh = output / "import.sh"
        import_content = "#!/bin/bash\n# Run these commands to import existing resources into Terraform state\n\n"
        import_content += "\n".join(import_commands)
        import_sh.write_text(import_content)
        console.print(f"  Written: {import_sh}")

    console.print("\n[yellow]Next steps:[/yellow]")
    console.print("  1. Review generated files")
    console.print("  2. Run: terraform init")
    console.print("  3. Run: bash import.sh")
    console.print("  4. Run: terraform plan")
    console.print()


@app.command("ansible")
def export_ansible(
    output: Path = typer.Option(None, "--output", "-o", help="Output directory (default: ./ansible/inventory)"),
):
    if output is None:
        output = ANSIBLE_DIR
    """Generate Ansible inventory from existing droplets."""
    client = get_client()

    output.mkdir(parents=True, exist_ok=True)

    console.print(f"\n[bold]Exporting to Ansible[/bold] -> {output}\n")

    droplets = client.droplets.list().get("droplets", [])

    if not droplets:
        console.print("[yellow]No droplets found[/yellow]")
        return

    # Group by tags
    groups: dict[str, list] = {"all": []}

    for d in droplets:
        ip = d["networks"]["v4"][0]["ip_address"] if d["networks"]["v4"] else None
        if not ip:
            continue

        host_entry = {
            "name": d["name"],
            "ip": ip,
            "id": d["id"],
            "region": d["region"]["slug"],
        }

        groups["all"].append(host_entry)

        for tag in d.get("tags", []):
            if tag not in groups:
                groups[tag] = []
            groups[tag].append(host_entry)

    # Generate INI inventory
    inventory_content = "# Generated by dom export ansible\n\n"

    for group, hosts in groups.items():
        inventory_content += f"[{group}]\n"
        for h in hosts:
            inventory_content += f"{h['name']} ansible_host={h['ip']} # id={h['id']} region={h['region']}\n"
        inventory_content += "\n"

    inventory_file = output / "inventory.ini"
    inventory_file.write_text(inventory_content)
    console.print(f"  Written: {inventory_file}")

    # Generate YAML inventory too
    yaml_content = "# Generated by dom export ansible\nall:\n  hosts:\n"
    for h in groups["all"]:
        yaml_content += f"    {h['name']}:\n"
        yaml_content += f"      ansible_host: {h['ip']}\n"
        yaml_content += f"      do_id: {h['id']}\n"
        yaml_content += f"      do_region: {h['region']}\n"

    yaml_file = output / "inventory.yml"
    yaml_file.write_text(yaml_content)
    console.print(f"  Written: {yaml_file}")

    console.print(f"\n  [green]Total hosts:[/green] {len(groups['all'])}")
    console.print("\n[yellow]Usage:[/yellow]")
    console.print(f"  ansible -i {inventory_file} all -m ping")
    console.print()
